<a href="https://colab.research.google.com/github/radhaete/python/blob/main/python_advance_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Data structure
# scalar=single value array
# vector=single/one dimensional array row/column(1D)
# Matric=two dimensional array(2D)
# Tensor=Multi dimensional array(3D)
import numpy as np



In [ ]:
np.array([1,2,3])

array([1, 2, 3])

In [ ]:
np.array((1,2,3))

array([1, 2, 3])

In [ ]:
# scalar
np.array([1])


array([1])

In [ ]:
# vector
a=(np.array([1,2,3]))
print(a)
type(a)

[1 2 3]


numpy.ndarray

In [ ]:
b=np.array([[1,2,3]])
b.T

array([[1],
       [2],
       [3]])

In [ ]:
type(b)

numpy.ndarray

In [ ]:
m=np.matrix([[1,2,3],[4,5,6]])
m

matrix([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
type(m)

numpy.matrix

In [ ]:
m.shape

(2, 3)

In [ ]:
# Arrays
a=np.array([[1,2,3],[4,5,6]])
a
type(a)

numpy.ndarray

In [ ]:
a.ndim

2

In [ ]:
b=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
b


array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [ ]:
b.ndim

3

In [ ]:
b.shape

(1, 3, 3)

In [ ]:
b.size

9

In [ ]:
a=np.zeros((3,3))
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
b=np.ones((3,3))
b

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
c=np.full((3,3),9)
c

array([[9, 9, 9],
       [9, 9, 9],
       [9, 9, 9]])

In [ ]:
d=np.arange(10,20)
d

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [ ]:
e=np.linspace(20,50,9)
e

array([20.  , 23.75, 27.5 , 31.25, 35.  , 38.75, 42.5 , 46.25, 50.  ])

In [ ]:
f=np.array([np.arange(1,10,2),np.linspace(20,30,5)])
f

array([[ 1. ,  3. ,  5. ,  7. ,  9. ],
       [20. , 22.5, 25. , 27.5, 30. ]])

In [ ]:
# Accessing values from array
a=np.array([np.linspace(1,10,3),np.linspace(20,30,3),np.linspace(30,40,3)])
a

array([[ 1. ,  5.5, 10. ],
       [20. , 25. , 30. ],
       [30. , 35. , 40. ]])

In [ ]:
a.ndim

2

In [ ]:
a.shape

(3, 3)

In [ ]:
a[0]

array([ 1. ,  5.5, 10. ])

In [ ]:
a[0,0]

np.float64(1.0)

In [ ]:
a[2,1]

np.float64(35.0)

In [ ]:
a[:2,:2]

array([[ 1. ,  5.5],
       [20. , 25. ]])

In [ ]:
a[:1,:2]

array([[1. , 5.5]])

In [ ]:
a

array([[ 1. ,  5.5, 10. ],
       [20. , 25. , 30. ],
       [30. , 35. , 40. ]])

In [ ]:
# Boolean index in array
a>10

array([[False, False, False],
       [ True,  True,  True],
       [ True,  True,  True]])

In [ ]:
b=[1,2,3,4,5,6,7,8]
b

[1, 2, 3, 4, 5, 6, 7, 8]

In [ ]:
b>2

TypeError: '>' not supported between instances of 'list' and 'int'

In [ ]:
for i in b:
  if i>2:
    print(i)

3
4
5
6
7
8


In [ ]:
a[a>10]

array([20., 25., 30., 30., 35., 40.])

In [ ]:
expr=a>10

In [ ]:
print("values >10 in array A is",a[expr])

values >10 in array A is [20. 25. 30. 30. 35. 40.]


In [ ]:
# Elementwise operation
scalar=np.array(10)
scalar

array(10)

In [ ]:
scalar+10

np.int64(20)

In [ ]:
scalar-10

np.int64(0)

In [ ]:
scalar*10

np.int64(100)

In [ ]:
vector=np.array([1,2,3,4,5])
vector

array([1, 2, 3, 4, 5])

In [ ]:
a=[1,2,3,4,5]
a+10

TypeError: can only concatenate list (not "int") to list

In [ ]:
vector-10

array([-9, -8, -7, -6, -5])

In [ ]:
vector/10

array([0.1, 0.2, 0.3, 0.4, 0.5])

In [ ]:
# Matrix
m=np.array([[1,2,3],[4,5,6]])
m

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
m+10

array([[11, 12, 13],
       [14, 15, 16]])

In [ ]:
m-10

array([[-9, -8, -7],
       [-6, -5, -4]])

In [ ]:
m*10

array([[10, 20, 30],
       [40, 50, 60]])

In [ ]:
# Broadcasting & stacking
a=np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [ ]:
a.shape

(2, 2)

In [ ]:
b=np.array([5,6])
b

array([5, 6])

In [ ]:
b.shape

(2,)

In [ ]:
b.T.shape

(2,)

In [ ]:
c=np.concatenate((a,b.reshape(1,2)),axis=0)
print(c)

[[1 2]
 [3 4]
 [5 6]]


In [ ]:
d=np.concatenate((a,b.reshape(2,1)),axis=1)
print(d)

[[1 2 5]
 [3 4 6]]


In [ ]:
np.vstack((a,b))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
np.hstack((a,b.reshape(-1,1)))

array([[1, 2, 5],
       [3, 4, 6]])

In [ ]:
a+b

array([[ 6,  8],
       [ 8, 10]])

In [ ]:
a=np.random.randint(1,20,(3,3))
a

array([[11,  9, 14],
       [ 8,  5,  8],
       [11, 19,  7]])

In [ ]:
a.sum()

np.int64(92)

In [ ]:
print("column wise addition",a.sum(axis=0))
print("row wise addition",a.sum(axis=1))


column wise addition [30 33 29]
row wise addition [34 21 37]


In [ ]:
c.mean()

np.float64(3.5)

In [ ]:
c.std()

np.float64(1.707825127659933)

In [ ]:
c.min()

np.int64(1)

In [ ]:
c.max()

np.int64(6)

In [ ]:
# Numereical Python(numpy)
# packages=collection of similar classes
# Reshape,ravel,Split,Random
a=np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
import numpy as np
b=np.arange(1,10)
b.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
a=np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
# Ravel=convert 2D array to 1D array
a.ravel()

array([1, 2, 3, 4, 5, 6])

In [ ]:
c=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
c

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [ ]:
c.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# split
a=np.arange(1,20,2)
a

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [ ]:
np.split(a,2)

[array([1, 3]),
 array([5, 7]),
 array([ 9, 11]),
 array([13, 15]),
 array([17, 19])]

In [ ]:
np.split(a,(3,6,19))

[array([1, 3, 5]),
 array([ 7,  9, 11]),
 array([13, 15, 17, 19]),
 array([], dtype=int64)]

In [ ]:
# Random
np.random.randn(3,3)

array([[ 0.90969144,  0.54061589, -0.89048152],
       [-0.38185924, -0.06705886, -0.41583435],
       [-1.07504818,  1.53112927,  0.02009414]])

In [ ]:
np.random.sample((3,3))

array([[0.73700312, 0.58329481, 0.4266858 ],
       [0.94486332, 0.88788573, 0.59265807],
       [0.78220885, 0.28711164, 0.79188239]])

In [ ]:
np.random.seed(1)
a=np.random.randint(1,20,(3,3))
a

array([[ 6, 12, 13],
       [ 9, 10, 12],
       [ 6, 16,  1]])

In [ ]:
a

array([[ 6, 12, 13],
       [ 9, 10, 12],
       [ 6, 16,  1]])

In [ ]:
# mostly used SEED function
rng=np.random.default_rng(1)
b=rng.integers(1,50,(3,3))
b

array([[24, 26, 38],
       [47,  2,  8],
       [41, 47, 13]])

In [ ]:
# python is object oriented programme
# Packages/modules/libraries=collection of similar classes
# collection of similar values/ methods
# classes=blueprint=design=plan
# Instances=objects=physical entities
           # Classes & object
class employee:
  com="ou"
  def greeting(self):
    return "welcome to python"
emp=employee()
print("company of the emp is :",emp.com)
print("greeting from the company is:",emp.greeting())



company of the emp is : ou
greeting from the company is: welcome to python


In [ ]:
class employee:
  com="ou"
  def greeting(self):
    return "welcome to python"
emp=employee()
print("company of the emp is:",emp.com)
print("greeting from the company is:",emp.greeting())

company of the emp is: ou
greeting from the company is: welcome to python


In [ ]:
class students:
  s1="r"
  s2="v"
  s3="n"
  s4="c"
  def greeting(self):
    print("welcome to python")
stu=students()
print("name of the students:",stu.s1)
print("name of the students:",stu.s2)
print("name of the students:",stu.s3)
print("name of the students:",stu.s4)
print(stu.greeting())



name of the students: r
name of the students: v
name of the students: n
name of the students: c
welcome to python
None


In [ ]:
class Students:
    s1 = "r"
    s2 = "v"
    s3 = "n"
    s4 = "c"

    def greeting(self):
        print("welcome to python")


# object creation
obj = Students()
obj.greeting()


welcome to python


In [ ]:
def caluculator(x,y):
  x=int(input("enter x:"))
  y=int(input("enter y:"))
  operation=int(input("1.addition | 2.subtraction"))
  if operation==1:
    print(f"addition of {x} and {y} is {x+y}")
  else :
    print(f"subtraction of {x} and {y} is {x-y}")
caluculator("x","y")


enter x:5
enter y:7
1.addition | 2.subtraction2
subtraction of 5 and 7 is -2


In [ ]:
# Constructor/instances
class employee:
  company="OU"
  def greeting(self):
    return f"welcome to python"
emp=employee()
print("company name is:",emp.company)
print("greeting from the company is:",emp.greeting())
emp.greeting()

company name is: OU
greeting from the company is: welcome to python


'welcome to python'

In [ ]:
class employee:
  def __init__(self,name,age,gender):
    self.name=name
    self.age=age
    self.gender=gender
  def welcome(self):
    return f"{self.name} is a {self.gender} at the age of {self.age}"
emp=employee("Radha","female",35)
print("Name of the employee is:",emp.name)
print(" Gender of the employee is:",emp.gender)
print("Age of the employee is:",emp.age)
emp.welcome()

Name of the employee is: Radha
 Gender of the employee is: 35
Age of the employee is: female


'Radha is a 35 at the age of female'

In [ ]:
class employee:
  company="ou"
  def greeting(self):
    return f"welcome to python"
emp=employee()
print("Name of the company is:",emp.company)
print("Greeting from the company is:",emp.greeting())
emp.greeting()

Name of the company is: ou
Greeting from the company is: welcome to python


'welcome to python'

In [ ]:
class employee:
  def __init__(self,name,gender,age):
    self.name=name
    self.gender=gender
    self.age=age
  def welcome(self):
    return f"{self.name} is a {self.gender} working at the age of {self.age}"
emp2=employee("radha","female",29)
print("Name of the employee is:",emp2.name)
print("Gender of the employee is:",emp2.gender)
print("Age of the employee is:",emp2.age)
emp2.welcome()


Name of the employee is: radha
Gender of the employee is: female
Age of the employee is: 29


'radha is a female working at the age of 29'

In [ ]:
emp.greeting()

AttributeError: 'employee' object has no attribute 'greeting'

In [ ]:
emp2.welcome()

'radha is a female working at the age of 29'

In [ ]:
# Inheritance
class parent:
  def __init__(self,name,gender,age):
    self.name=name
    self.gender=gender
    self.age=age
  def welcome(self):
    return f"welcome to python"
  def custom(self):
    return f"{self.name} is a {self.gender} working at the age of {self.age}"
class child(parent):
   pass
p=parent("Radha","Female",35)
print(p.name)
print(p.gender)
print(p.age)
print(p.welcome())
print(p.custom())
ch=child("Chinnu","male",7)
print(ch.name)
print(ch.gender)
print(ch.age)
print(ch.welcome())
print(ch.custom())

Radha
Female
35
welcome to python
Radha is a Female working at the age of 35
Chinnu
male
7
welcome to python
Chinnu is a male working at the age of 7


In [ ]:
# Inheritance
class parent:
  def __init__(self,name,gender,age):
    self.name=name
    self.gender=gender
    self.age=age
  def custom(self):
    return f"{self.name} is a {self.gender} working at the age of {self.age}"
class child(parent):
   pass
p=parent("Radha","Female",35)
print(p.name)
print(p.gender)
print(p.age)
print(p.custom())
ch=child("Chinnu","male",7)
print(ch.name)
print(ch.gender)
print(ch.age)
print(ch.custom())

Radha
Female
35
Radha is a Female working at the age of 35
Chinnu
male
7
Chinnu is a male working at the age of 7


In [ ]:
class bmw:
   company="British Motors"
   def greeting(self):
    return f"welcome to british motors"
class Audi:
   company="British Motors"
   def greeting(self):
    return f"welcome to british motors"
class Tata:
   company="British Motors"
   def greeting(self):
    return f"welcome to british motors"
bmw=BMW()
Audi=AUDI()
Tata=TATA()
for i in (bmw,Audi,Tata):
  print("company:",i.company())
  print("greeting",i.greeting())

NameError: name 'BMW' is not defined

In [ ]:
def funct(n):
  total=0
  for i in range(n+1):
    total+=i
  return total
print(funct(5))

15


In [ ]:
# Q1):Take a list of integers and return sum of all even numbers
lst=[1,2,3,4,5]
def sum_even_nums(lst):
    even_sum=0
    for i in lst:
      if i%2==0:
        even_sum+=i
    return even_sum
result=sum_even_nums(lst)
print(result)
          # or
def sum_even_numbers(numbers):
    return sum(i for i in numbers if i % 2 == 0)


6


In [ ]:

def funcRecursive(n):
    if n == 0:
        return 0
    else:
        return n + funcRecursive(n - 1)

print(funcRecursive(5))





15


In [ ]:
def funcRecursive(n):
  if n==0:
    return 0
  else:
    return n+funcRecursive(n-1)
print(funcRecursive(5))



15


In [ ]:
# Q2:WAp to find factorial of a number using recursive function
def funcRecursive(n):
  if n==1:
    return 1
  else:
   return n*funcRecursive(n-1)
print(funcRecursive(5))

120


In [ ]:
def funcRecursive(n):
  if n==0:
    return 0
  else:
    return n+funcRecursive(n-1)
print(funcRecursive(5))
# and
def funcRecursive(n):
  if n==1 or n==0:
    return 1
  else:
    return n*funcRecursive(n-1)
print(funcRecursive(5))


15
120


In [ ]:
# Q3:write a recursive function in python to compute the numbers in the fibonacci seqence,where the first two numbers
# in the sequence are 0 and 1 and each subsequent number is the sum of the previous two:
def fibonacci(n):
  if n  <=1:
    return n
  else:
    return fibonacci(n-1)+fibonacci(n-2)
print(fibonacci(11))



89


In [ ]:
#Lambda Function:  lambda arguments:expression
# 1.Known as anonymous function as defined without name.
# 2.Can accept any number of arguments,but expression has only one value.
#  Q4:WAP called plus_age that takes an input age and returns the age plus 10.
plus_age=lambda age:age+10
print(plus_age(25))



35


In [ ]:
# Q5:Write a lambda function in python to calculate the area of rectangle give its length and width.
rect_area=lambda l,b:l*b
print(rect_area(4,5))

20


In [ ]:
# Q6:WAP a lambda function in python called greater that takes two input numbers a and b and returns the greater of the two.
greater=lambda a,b:a if a>b else b
print(greater(8,6))

8


In [ ]:
# Q7:Create adictionary containing gender and age info.It should be
List_of_gender_age=[
{"gender":"m","age":20},\
{"gender":"f","age":35},\
{"gender":"m","age":30},\
{"gender":"f","age":32}]
print(List_of_gender_age)

[{'gender': 'm', 'age': 20}, {'gender': 'f', 'age': 35}, {'gender': 'm', 'age': 30}, {'gender': 'f', 'age': 32}]


In [ ]:
# Q8.WAP a code to get the output of students age variable created in above.
ages=[i["age"] for i in List_of_gender_age]
print(ages)

[20, 35, 30, 32]


In [ ]:
# High order function
  # In python it is a function as arguments or return a function as its result.
  # Map
  # It takes a function and iterable as arguments and apllies the function to each element in the iterable,returning a new iterable.
numbers=[1,2,3,4,5]
def doub_num(num):
  return num*2
doubled_num=list(map(doub_num,numbers))
print(doubled_num)



[2, 4, 6, 8, 10]


In [ ]:
# Q:WAP that uses a map function to convert a tuple of wts in pounds(173,154,112,340,230) to a tuple of wts in kgs.The conversion formula forn pounds to kgs is
# kgs*pounds/2.2.The output should be rounded to 2 decimal places.
pounds=(173,154,112,340,230)
def wt_kgs(i):
  return round(i/2.2 ,2)
wts_in_kgs=tuple(map(wt_kgs,pounds))
print(wts_in_kgs)
# or
pounds=(173,154,112,340,230)
wt_kgs=tuple(map(lambda x:round(x/2.2,2),pounds))
print(wt_kgs)

(78.64, 70.0, 50.91, 154.55, 104.55)
(78.64, 70.0, 50.91, 154.55, 104.55)


In [ ]:
# Q:WAP to get the output of male students variable created in
# List_of_gender_age=[
# {"gender":"m","age":20},\
# {"gender":"f","age":35},\
# {"gender":"m","age":30},\
# {"gender":"f","age":32}]
# print(List_of_gender_age)
def male(n):
  if n["gender"]=="m":
    return True
  else:
    return False
male_n=list(filter(male,List_of_gender_age))
print(male_n)
# or
# Filter with lambda
male=lambda n:True if n["gender"]=="m" else False
male_n=list(filter(male,List_of_gender_age))
print(male_n)

[{'gender': 'm', 'age': 20}, {'gender': 'm', 'age': 30}]
[{'gender': 'm', 'age': 20}, {'gender': 'm', 'age': 30}]


In [ ]:
fruits=["apple","orange","lemon","soda"]
fruit=tuple(filter(lambda n:"e" in n,fruits))
fruit

('apple', 'orange', 'lemon')

In [ ]:
# Reduce: Useful when we need to apply a function to an iterable and reduce it to asingle cumulative value.
from functools import reduce
num=[1,2,3,4,5]
total=reduce(add,num)
print(total)

15


In [ ]:
def add(x,y):
 return x+y
nums=[1,2,3,4,5]
total=(add,num)
print(total)

(<function add at 0x7f4e558a5080>, [5, 10, 15, 20])


In [ ]:
from functools import functools
l=[12,23,34,45,56,67,78,89,90]
functools.reduce(lambda x,y:x if x>y else y,l)
functools.reduce(lambda x,y:x if x<y else y,l)

12

In [ ]:
# Q:WAP to filter the given list that contains only those ages that are greaterthan 60 or lessthan 30.The given list
ages=[25,65,82,42,33]
great_60=list(filter(lambda x: x>60,ages))
print(great_60)

[65, 82]


In [ ]:
# Q:WAP to find the max weight in pounds from a given tuple wt_pound.
wt_pound=(173,154,207,567,890)
max_wt=functools.reduce(lambda x,y:x if x>y else y,wt_pound)
print("max_wt in pound:",max_wt)

max_wt in pound: 890


In [ ]:
male=lambda n:True if n["gender"]=="m" else False
male_n=list(filter(male,List_of_gender_age))
print(male_n)
# or
gender=["f","m","f","m","f","m","m"]
def male(n):
  return n=="m"
males=list(filter(male,gender))
print(males)

[{'gender': 'm', 'age': 20}, {'gender': 'm', 'age': 30}]
['m', 'm', 'm', 'm']


In [ ]:
# Q:WA lambda function to find only even number from a list.
lst=[1,2,3,4,5,6,7,8,9]
even_num=list(filter(lambda n:n%2==0,lst))
print(even_num)

[2, 4, 6, 8]


In [ ]:
# Q:WA lambda funct to find only negative numbers from list
neg_list=[0,-1,2,-3,4,-5,6,-7,8,-9]
negative_num=list(filter(lambda n: n<0,neg_list))
print(negative_num)


[-1, -3, -5, -7, -9]


In [ ]:
# Dot 1 array multipy with 1 scalar.
# multiply 2 arrays is with multiply symbol *.
a=np.array([1,2,3])
b=2
dot_product=np.dot(a,b)
print("dot product is:",dot_product)

dot product is: [2 4 6]


In [ ]:
# Boolean array
a=np.array([[[1,2],[3,4],[5,6]]])
a> 2

array([[[False, False],
        [ True,  True],
        [ True,  True]]])

In [ ]:
array=np.arange(16).reshape(4,4)
array

# shape()=In DataFrame tells about(rows,columns) Pandas.
# Reshape()=In Numpy array allows to change the shape like reshape.


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
# shape()=In DataFrame tells about(rows,columns) Pandas.
# Reshape()=In Numpy array allows to change the shape like reshape.
# splitting
x=np.arange(25).reshape(5,5)
print(x,"\n\n")
np.hsplit(x,1)
np.hsplit(x,2)
np.hsplit(x,3)
np.hsplit(x,4)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]] 




ValueError: array split does not result in an equal division

In [ ]:
print(np.sort(x,axis=0))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [ ]:
# Identify Matrix
# An identify matrix is a square matrix where all
# the diagonal elements are 1and other elements are 0.In numpyyou can create an identify matrix using the numpy.identify()
# or np.eye()function
np.eye(4)
np.identify(4)
np.eye(4,k=1)

AttributeError: module 'numpy' has no attribute 'identify'

In [ ]:
# flipping an array
print(np.flip(a,axis=1|0))

[[[5 6]
  [3 4]
  [1 2]]]


In [ ]:
print(a.shape)

(1, 3, 2)


In [ ]:
print(b.shape)

AttributeError: 'int' object has no attribute 'shape'

In [ ]:
# Broadcasting-makes the smaller array same in size as the bigger array before the operation.
# Q:Create two lists with 4 elements and add them not concatenate them.
a=[1,2,3,4]
b=[10,11,12,13]
print(a+b)

[1, 2, 3, 4, 10, 11, 12, 13]


In [ ]:
# Q:create 2 lists with 4 elements with 4 elements and add them by perfoming elementwise operation.
a=[1,2,3,4]
b=[10,11,12,13]
for i,j in zip(a,b):
  c=i+j
  print(c)

11
13
15
17


In [ ]:
# Q:Create & print an array with multiple values and also print dimension,size,shape of array.
import numpy as np
a=np.array([25,26,27])
print(a)
print(a.ndim)
print(a.shape)
print(a.size)

[25 26 27]
1
(3,)
3


In [ ]:
# Q:Create & print Multidimensional array with multiple values(atleast 2 *2) .
# Also print the dimensions,size & shape of the array.
a=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(a)
print(a.ndim)
print(a.shape)
print(a.size)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
3
(1, 3, 3)
9


In [ ]:
# Check the multidimesion array
a_matrix=np.matrix([1,2,3],[4,5,6])
print(a_matrix)
print(type(a_matrix))

TypeError: Field elements must be 2- or 3-tuples, got '4'

In [ ]:
# Create a multiD array (3row,4col) of ones
import numpy as np
a=np.ones(shape=[3,4])
print(a)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
# create a multiD array(3,4) zeroes
a=np.zeroes(shape=[3,4])
print(a)

AttributeError: module 'numpy' has no attribute 'zeroes'